services:
  - type: static
    name: frontend-app
    region: singapore
    buildCommand: rm -rf node_modules package-lock.json && npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://api.dtv2405.id.vn

